import = ["/home/oung/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13.5

[font.normal]
family = "JetBrainsMono NF"
style = "Medium"

[font.offset]
x = -1
y = 0

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Shift|Control"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95
title = "Alacritty"

[window.padding]
x = 0
y = 0
